# Generated by Django 5.0.6 on 2024-06-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(upload_to="media/product_images/"),
        ),
    ]
